### PR TITLE
feat: Add support for Built-in control flow syntax (#26)

### PR DESCRIPTION
**Pull request by pmpak**
BREAKING CHANGE
- minimum angular version required bumped to 17
- minimum node version required bumped to v18.13.0 to be aligned with the Angular 17 requirements
- minimum TypeScript version required bumped to v5.2 to be aligned with the Angular 17 requirements

### CODE REVIEW

**Comment by pmpak** [comment]
Closes #26

Because I needed to use imports that don't exist in Angular <= 16 I had to bump up the minimum required version for Angular, Node and TypeScript which leads to a major update in case we proceed on merging it.
In case this is undesirable I could approach it differently but this could lead to a more verbose and fragile workarounds.

@michaelbromley how would you prefer to proceed?

**Comment by michaelbromley** [comment]
Wow amazing! Thank you! 
Since this change only becomes relevant in the case of a major change to an Angular codebase, I think it makes sense that we make this a major bump for this lib too.

One small thing: the test fail in CI because the [workflow file](https://github.com/vendure-ecommerce/ngx-translate-extract/blob/master/.github/workflows/node.js.yml#L12) specifies node v16.x Could you update this as part of this PR to at least 18.x (you could also add v20.x so we are covering that version too).

**Comment by pmpak** [comment]
The workflow file slipped my attention. I updated now the node versions and the versions in the compatibility table in the README.md

**Comment by michaelbromley** [comment]
Thanks! There's an annoying CI failure here though: https://github.com/vendure-ecommerce/ngx-translate-extract/actions/runs/6944504102/job/18892782835?pr=27#step:5:9

**Comment by michaelbromley** [comment]
Great! I'll do a release shortly 👍

**Comment by pmpak** [comment]
Thank you very much! In the meantime I will make some more tests in a project and fingers crossed there are no strange edge cases.

**Pull request merged**
